# Site settings
title: ausloos.kim
description: >
    ausloos.kim
author: Kim Ausloos
email: kim@thanatos.be
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ausloos.kim" # the base hostname & protocol for your site
twitter_username: kamme
github_username:  kimausloos

# Build settings
include: [_pages]
markdown: kramdown
permalink: /:year/:month/:title
sass:
    style: compressed

plugins:
  - jekyll-gist
  - jekyll-paginate

gist:
  noscript: false
